name: Blog Post Entries

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        
    - name: Checkout source files
      uses: actions/checkout@v2

    - name: Show files
      run:  set ; pwd ; ls -l

    - name: Install requirements
      run:  |
        pip install -r requirements.txt;
        sudo apt install prettier

    - name: Build static pages
      run:  |
        python3 build.py;
        ./prettify.sh

    - name: Commit GitHub Pages
      uses: EndBug/add-and-commit@v9
      with:
        add: .
        committer_name: GitHub Actions
        committer_email: actions@github.com
